# Generated by Django 3.0.2 on 2020-01-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
