# Generated by Django 3.0.2 on 2020-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200124_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
